"""
export_model.py
----------------
Exports the trained TF-IDF vectorizer + Logistic Regression classifier into
docs/model.js, so the exact same model can run inside the browser (used by
the static GitHub Pages version of the site - no backend needed).

Run:  python export_model.py
"""

import json
import os
import joblib
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

MODEL_DIR = "models"
OUT_PATH = os.path.join("docs", "model.js")


def main():
    vec_path = os.path.join(MODEL_DIR, "vectorizer.joblib")
    clf_path = os.path.join(MODEL_DIR, "classifier.joblib")
    if not (os.path.exists(vec_path) and os.path.exists(clf_path)):
        import train_model
        train_model.train()

    vectorizer = joblib.load(vec_path)
    classifier = joblib.load(clf_path)

    vocab = {term: int(idx) for term, idx in vectorizer.vocabulary_.items()}
    payload = {
        "vocab": vocab,
        "idf": [float(x) for x in vectorizer.idf_],
        "coef": [float(x) for x in classifier.coef_[0]],
        "intercept": float(classifier.intercept_[0]),
        "stopWords": sorted(ENGLISH_STOP_WORDS),
    }

    os.makedirs("docs", exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by export_model.py - do not edit by hand.\n")
        f.write("window.AEGIS_MODEL = ")
        json.dump(payload, f)
        f.write(";\n")
    print(f"Exported {len(vocab)} features to {OUT_PATH} "
          f"({os.path.getsize(OUT_PATH) / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
